import { useState, useMemo } from 'react'; import { motion } from 'framer-motion'; import { ClipboardList, Plus, Trash2 } from 'lucide-react'; import { useApp, generateId } from '../context/AppContext'; import Modal from '../components/Modal';
export default function Commitments() {
  const { students, engagements, addEngagement, deleteEngagement } = useApp(); const [isModal, setIsModal] = useState(false);
  const [form, setForm] = useState({ studentId:'', deadline:'', amount:'', parent:'' });
  const handleSubmit = () => { if (!form.studentId || !form.amount) return; addEngagement({ id: generateId(), studentId: form.studentId, deadline: form.deadline, amount: Number(form.amount), parent: form.parent, status: 'Actif' }); setIsModal(false); setForm({ studentId:'', deadline:'', amount:'', parent:'' }); };
  return (
    <div>
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-white mb-1">Suivi des engagements</h2><p className="text-slate-400 text-sm">{engagements.length} engagements enregistrés</p></div><button onClick={() => setIsModal(true)} className="btn-gold rounded-xl px-5 py-2.5 flex items-center gap-2 text-sm"><Plus size={18} /> Nouvel engagement</button></div>
      <div className="glass-panel rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Élève</th><th>Classe</th><th>Échéance</th><th>Montant</th><th>Parent / Tuteur</th><th>Statut</th><th></th></tr></thead><tbody>
        {engagements.map((e, i) => { const s = students.find(x => x.id === e.studentId); return (<motion.tr key={e.id} initial={{ opacity:0, x:-20 }} animate={{ opacity:1, x:0 }} transition={{ delay:i*0.03 }}><td className="font-medium text-white">{s?.name||'—'}</td><td><span className="badge-blue">{s?.class||'—'}</span></td><td>{e.deadline}</td><td className="font-semibold text-amber-400">{e.amount.toLocaleString('fr-FR')} F</td><td>{e.parent}</td><td>{e.status==='Actif'?<span className="badge-amber">{e.status}</span>:e.status==='Honoré'?<span className="badge-green">{e.status}</span>:<span className="badge-red">{e.status}</span>}</td><td><button onClick={() => deleteEngagement(e.id)} className="p-2 rounded-lg hover:bg-red-500/10 text-red-400"><Trash2 size={16} /></button></td></motion.tr>); })}
      </tbody></table></div>{engagements.length===0 && <div className="p-12 text-center"><ClipboardList className="mx-auto mb-4 text-slate-600" size={48} /><p className="text-slate-500">Aucun engagement trouvé</p></div>}</div>
      <Modal isOpen={isModal} onClose={() => setIsModal(false)} title="Nouvel engagement"><div className="space-y-4"><div><label className="block text-sm text-slate-400 mb-1">Élève *</label><select value={form.studentId} onChange={e => setForm({...form,studentId:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{students.filter(s => s.active!==false).map(s => <option key={s.id} value={s.id}>{s.name} ({s.class})</option>)}</select></div><div><label className="block text-sm text-slate-400 mb-1">Échéance</label><input type="date" value={form.deadline} onChange={e => setForm({...form,deadline:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" /></div><div><label className="block text-sm text-slate-400 mb-1">Montant (FCFA) *</label><input type="number" value={form.amount} onChange={e => setForm({...form,amount:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="0" /></div><div><label className="block text-sm text-slate-400 mb-1">Parent / Tuteur</label><input value={form.parent} onChange={e => setForm({...form,parent:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Nom du parent" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsModal(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleSubmit} className="btn-gold rounded-xl px-6 py-2.5">Enregistrer</button></div></Modal>
    </div>
  );
}
