import { useState, useMemo } from 'react'; import { motion } from 'framer-motion'; import { Plus, Trash2, Wallet, Users, DollarSign } from 'lucide-react'; import { useApp, generateId } from '../context/AppContext'; import Modal from '../components/Modal';
export default function Payroll() {
  const { employees, salaryPayments, salaryAdvances, addEmployee, addSalaryPayment, addSalaryAdvance, deleteEmployee } = useApp();
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [isEmp, setIsEmp] = useState(false); const [isPay, setIsPay] = useState(false); const [isAdv, setIsAdv] = useState(false);
  const [empForm, setEmpForm] = useState({ name:'', function:'', phone:'', monthlySalary:'' });
  const [payForm, setPayForm] = useState({ employeeId:'', date:'', amount:'' });
  const [advForm, setAdvForm] = useState({ employeeId:'', date:'', amount:'', observation:'' });
  const monthPayments = useMemo(() => salaryPayments.filter(p => p.month === month), [salaryPayments, month]);
  const monthTotal = monthPayments.reduce((s, p) => s + p.amount, 0);
  const handleEmp = () => { if (!empForm.name) return; addEmployee({ id: generateId(), name: empForm.name, function: empForm.function, phone: empForm.phone, monthlySalary: Number(empForm.monthlySalary) || 0, active: true }); setIsEmp(false); setEmpForm({ name:'', function:'', phone:'', monthlySalary:'' }); };
  const handlePay = () => { if (!payForm.employeeId || !payForm.amount) return; addSalaryPayment({ id: generateId(), employeeId: payForm.employeeId, date: payForm.date || new Date().toISOString().split('T')[0], amount: Number(payForm.amount), month }); setIsPay(false); setPayForm({ employeeId:'', date:'', amount:'' }); };
  const handleAdv = () => { if (!advForm.employeeId || !advForm.amount) return; addSalaryAdvance({ id: generateId(), employeeId: advForm.employeeId, date: advForm.date || new Date().toISOString().split('T')[0], amount: Number(advForm.amount), observation: advForm.observation }); setIsAdv(false); setAdvForm({ employeeId:'', date:'', amount:'', observation:'' }); };
  return (
    <div>
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-white mb-1">Gestion des salaires</h2><p className="text-slate-400 text-sm">{employees.length} salariés enregistrés</p></div><div className="flex gap-3"><button onClick={() => setIsEmp(true)} className="btn-primary rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><Plus size={16} /> Salarié</button><button onClick={() => setIsPay(true)} className="btn-gold rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><Plus size={16} /> Salaire</button><button onClick={() => setIsAdv(true)} className="btn-primary rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><Plus size={16} /> Avance</button></div></div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-6">
        <div className="glass-card rounded-2xl p-6"><div className="w-10 h-10 rounded-xl bg-blue-500/20 flex items-center justify-center mb-4"><Users size={20} className="text-blue-400" /></div><p className="text-2xl font-bold text-white">{employees.length}</p><p className="text-sm text-slate-400">Salariés enregistrés</p></div>
        <div className="glass-card rounded-2xl p-6"><div className="w-10 h-10 rounded-xl bg-green-500/20 flex items-center justify-center mb-4"><DollarSign size={20} className="text-green-400" /></div><p className="text-2xl font-bold text-white">{monthTotal.toLocaleString('fr-FR')} F</p><p className="text-sm text-slate-400">Salaires du mois</p></div>
      </div>
      <div className="glass-panel rounded-xl p-4 mb-4 flex gap-4"><input type="month" value={month} onChange={e => setMonth(e.target.value)} className="input-glass rounded-xl px-4 py-2.5" /></div>
      <div className="glass-panel rounded-2xl overflow-hidden mb-6"><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Nom</th><th>Fonction</th><th>Téléphone</th><th>Salaire mensuel</th><th>Statut</th><th></th></tr></thead><tbody>
        {employees.map((e, i) => (<motion.tr key={e.id} initial={{ opacity:0, x:-20 }} animate={{ opacity:1, x:0 }} transition={{ delay:i*0.03 }}><td className="font-medium text-white">{e.name}</td><td>{e.function}</td><td>{e.phone}</td><td className="font-semibold text-amber-400">{e.monthlySalary.toLocaleString('fr-FR')} F</td><td>{e.active ? <span className="badge-green">Actif</span> : <span className="badge-red">Inactif</span>}</td><td><button onClick={() => deleteEmployee(e.id)} className="p-2 rounded-lg hover:bg-red-500/10 text-red-400"><Trash2 size={16} /></button></td></motion.tr>))}
      </tbody></table></div></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="glass-panel rounded-2xl p-6"><h3 className="text-lg font-semibold text-white mb-4">Paiements du mois</h3><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Date</th><th>Salarié</th><th>Montant</th></tr></thead><tbody>{monthPayments.map(p => { const e = employees.find(x => x.id === p.employeeId); return <tr key={p.id}><td>{p.date}</td><td className="text-white">{e?.name||'—'}</td><td className="text-green-400 font-semibold">{p.amount.toLocaleString('fr-FR')} F</td></tr>; })}</tbody></table></div></div>
        <div className="glass-panel rounded-2xl p-6"><h3 className="text-lg font-semibold text-white mb-4">Avances sur salaire</h3><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Date</th><th>Salarié</th><th>Montant</th><th>Observation</th></tr></thead><tbody>{salaryAdvances.map(a => { const e = employees.find(x => x.id === a.employeeId); return <tr key={a.id}><td>{a.date}</td><td className="text-white">{e?.name||'—'}</td><td className="text-amber-400 font-semibold">{a.amount.toLocaleString('fr-FR')} F</td><td>{a.observation}</td></tr>; })}</tbody></table></div></div>
      </div>
      <Modal isOpen={isEmp} onClose={() => setIsEmp(false)} title="Ajouter un salarié"><div className="space-y-4"><div><label className="block text-sm text-slate-400 mb-1">Nom *</label><input value={empForm.name} onChange={e => setEmpForm({...empForm,name:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Nom complet" /></div><div><label className="block text-sm text-slate-400 mb-1">Fonction</label><input value={empForm.function} onChange={e => setEmpForm({...empForm,function:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Poste" /></div><div><label className="block text-sm text-slate-400 mb-1">Téléphone</label><input value={empForm.phone} onChange={e => setEmpForm({...empForm,phone:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Numéro" /></div><div><label className="block text-sm text-slate-400 mb-1">Salaire mensuel (FCFA)</label><input type="number" value={empForm.monthlySalary} onChange={e => setEmpForm({...empForm,monthlySalary:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="0" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsEmp(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleEmp} className="btn-gold rounded-xl px-6 py-2.5">Ajouter</button></div></Modal>
      <Modal isOpen={isPay} onClose={() => setIsPay(false)} title="Enregistrer un salaire"><div className="space-y-4"><div><label className="block text-sm text-slate-400 mb-1">Salarié *</label><select value={payForm.employeeId} onChange={e => setPayForm({...payForm,employeeId:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></div><div><label className="block text-sm text-slate-400 mb-1">Date</label><input type="date" value={payForm.date} onChange={e => setPayForm({...payForm,date:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" /></div><div><label className="block text-sm text-slate-400 mb-1">Montant (FCFA) *</label><input type="number" value={payForm.amount} onChange={e => setPayForm({...payForm,amount:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="0" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsPay(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handlePay} className="btn-gold rounded-xl px-6 py-2.5">Enregistrer</button></div></Modal>
      <Modal isOpen={isAdv} onClose={() => setIsAdv(false)} title="Enregistrer une avance"><div className="space-y-4"><div><label className="block text-sm text-slate-400 mb-1">Salarié *</label><select value={advForm.employeeId} onChange={e => setAdvForm({...advForm,employeeId:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></div><div><label className="block text-sm text-slate-400 mb-1">Date</label><input type="date" value={advForm.date} onChange={e => setAdvForm({...advForm,date:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" /></div><div><label className="block text-sm text-slate-400 mb-1">Montant (FCFA) *</label><input type="number" value={advForm.amount} onChange={e => setAdvForm({...advForm,amount:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="0" /></div><div><label className="block text-sm text-slate-400 mb-1">Observation</label><input value={advForm.observation} onChange={e => setAdvForm({...advForm,observation:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Observation" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsAdv(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleAdv} className="btn-gold rounded-xl px-6 py-2.5">Enregistrer</button></div></Modal>
    </div>
  );
}
