import { useState, useMemo } from 'react'; import { motion } from 'framer-motion'; import { Stethoscope, Plus, Trash2, Hospital, Printer, RotateCcw } from 'lucide-react'; import { useApp, CLASSES, generateId } from '../context/AppContext'; import Modal from '../components/Modal';
export default function Stages() {
  const { students, stages, centers, addStage, deleteStage, addCenter, deleteCenter } = useApp();
  const [search, setSearch] = useState(''); const [classFilter, setClassFilter] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [isModal, setIsModal] = useState(false); const [isCenter, setIsCenter] = useState(false);
  const [form, setForm] = useState({ studentId:'', centerId:'', service:'', startDate:'', endDate:'', status:'Prévu' as const });
  const [cForm, setCForm] = useState({ name:'', service:'', capacity:'' });
  const filtered = useMemo(() => { let r = stages; if (search) { const q = search.toLowerCase(); r = r.filter(s => { const st = students.find(x => x.id === s.studentId); return st?.name?.toLowerCase().includes(q) || s.service.toLowerCase().includes(q); }); } if (classFilter) { r = r.filter(s => { const st = students.find(x => x.id === s.studentId); return st?.class === classFilter; }); } if (statusFilter) r = r.filter(s => s.status === statusFilter); return r; }, [stages, search, classFilter, statusFilter, students]);
  const handleSubmit = () => { if (!form.studentId || !form.centerId) return; addStage({ id: generateId(), studentId: form.studentId, centerId: form.centerId, service: form.service, startDate: form.startDate, endDate: form.endDate, status: form.status }); setIsModal(false); setForm({ studentId:'', centerId:'', service:'', startDate:'', endDate:'', status:'Prévu' }); };
  const handleCenter = () => { if (!cForm.name) return; addCenter({ id: generateId(), name: cForm.name, address: '', service: cForm.service, capacity: Number(cForm.capacity) || 0 }); setIsCenter(false); setCForm({ name:'', service:'', capacity:'' }); };
  const autoAllocate = () => {
    const eligible = students.filter(s => s.active !== false && !stages.some(st => st.studentId === s.id));
    eligible.forEach(s => {
      const avail = centers.filter(c => (stages.filter(st => st.centerId === c.id && st.service === c.service).length < c.capacity));
      if (avail.length) { const c = avail[0]; addStage({ id: generateId(), studentId: s.id, centerId: c.id, service: c.service, startDate: '', endDate: '', status: 'Prévu' }); }
    });
    alert('Répartition automatique effectuée !');
  };
  const statusOptions = ['Prévu','En cours','Terminé','Non fait','À reprendre'];
  const printStageSheet = () => {
    const html = `<html><head><title>Fiches de stage</title><style>body{font-family:Arial;padding:40px}h1{color:#1e40af;text-align:center}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #222;padding:7px}</style></head><body><h1>IPHES - Fiches de stage</h1><table><thead><tr><th>Élève</th><th>Classe</th><th>Structure</th><th>Service</th><th>Période</th><th>Statut</th></tr></thead><tbody>${filtered.map(s => { const st = students.find(x => x.id === s.studentId); const c = centers.find(x => x.id === s.centerId); return `<tr><td>${st?.name||'—'}</td><td>${st?.class||'—'}</td><td>${c?.name||'—'}</td><td>${s.service}</td><td>${s.startDate} → ${s.endDate}</td><td>${s.status}</td></tr>`; }).join('')}</tbody></table></body></html>`;
    const w = window.open('', '_blank'); if (w) { w.document.write(html); w.document.close(); w.print(); }
  };
  return (
    <div>
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-white mb-1">Gestion des stages</h2><p className="text-slate-400 text-sm">{filtered.length} stages enregistrés</p></div><div className="flex items-center gap-3"><img src="/3d-hospital-iso.png" alt="" className="w-12 h-12 object-contain opacity-60 hidden md:block" /><button onClick={() => setIsCenter(true)} className="btn-primary rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><Hospital size={16} /> Centres</button><button onClick={autoAllocate} className="btn-primary rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><RotateCcw size={16} /> Auto</button><button onClick={printStageSheet} className="btn-primary rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><Printer size={16} /> Fiches</button><button onClick={() => setIsModal(true)} className="btn-gold rounded-xl px-5 py-2.5 flex items-center gap-2 text-sm"><Plus size={18} /> Affecter</button></div></div>
      <div className="glass-panel rounded-xl p-4 mb-6 flex flex-col md:flex-row gap-4"><input type="text" value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher élève ou service..." className="flex-1 input-glass rounded-xl px-4 py-2.5" /><select value={classFilter} onChange={e => setClassFilter(e.target.value)} className="input-glass rounded-xl px-4 py-2.5"><option value="">Toutes les classes</option>{CLASSES.map(c => <option key={c} value={c}>{c}</option>)}</select><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="input-glass rounded-xl px-4 py-2.5"><option value="">Tous les statuts</option>{statusOptions.map(s => <option key={s} value={s}>{s}</option>)}</select></div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        <div className="lg:col-span-2 glass-panel rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Élève</th><th>Classe</th><th>Structure</th><th>Service</th><th>Période</th><th>Statut</th><th></th></tr></thead><tbody>
          {filtered.map((s, i) => { const st = students.find(x => x.id === s.studentId); const c = centers.find(x => x.id === s.centerId); return (<motion.tr key={s.id} initial={{ opacity:0, x:-20 }} animate={{ opacity:1, x:0 }} transition={{ delay:i*0.03 }}><td className="font-medium text-white">{st?.name||'—'}</td><td><span className="badge-blue">{st?.class||'—'}</span></td><td>{c?.name||'—'}</td><td>{s.service}</td><td className="text-sm">{s.startDate} → {s.endDate}</td><td>{s.status==='Terminé'?<span className="badge-green">{s.status}</span>:s.status==='En cours'?<span className="badge-blue">{s.status}</span>:s.status==='Prévu'?<span className="badge-amber">{s.status}</span>:<span className="badge-red">{s.status}</span>}</td><td><button onClick={() => deleteStage(s.id)} className="p-2 rounded-lg hover:bg-red-500/10 text-red-400"><Trash2 size={16} /></button></td></motion.tr>); })}
        </tbody></table></div>{filtered.length===0 && <div className="p-12 text-center"><Stethoscope className="mx-auto mb-4 text-slate-600" size={48} /><p className="text-slate-500">Aucun stage trouvé</p></div>}</div>
        <div className="glass-panel rounded-2xl p-6"><h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2"><Hospital size={20} className="text-amber-400" /> Centres et places</h3><div className="space-y-3">
          {centers.map(c => { const occupied = stages.filter(s => s.centerId === c.id && s.service === c.service).length; const remaining = c.capacity - occupied; return (
            <div key={c.id} className="glass-card rounded-xl p-4">
              <div className="flex justify-between items-start mb-2"><p className="font-medium text-white text-sm">{c.name}</p></div>
              <p className="text-xs text-slate-400 mb-2">{c.service}</p>
              <div className="flex items-center gap-3 text-xs"><span className="text-slate-400">Capacité: <span className="text-white">{c.capacity}</span></span><span className="text-slate-400">Occupées: <span className="text-amber-400">{occupied}</span></span><span className="text-slate-400">Restantes: <span className="text-green-400">{remaining}</span></span></div>
              <div className="mt-2 h-1.5 bg-slate-700 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-blue-500 to-amber-500 rounded-full" style={{ width: `${(occupied/c.capacity)*100}%` }} /></div>
              <button onClick={() => deleteCenter(c.id)} className="mt-2 text-xs text-red-400 hover:text-red-300">Supprimer</button>
            </div>
          ); })}
        </div></div>
      </div>
      <Modal isOpen={isModal} onClose={() => setIsModal(false)} title="Affecter un stage"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Élève *</label><select value={form.studentId} onChange={e => setForm({...form,studentId:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{students.filter(s => s.active!==false).map(s => <option key={s.id} value={s.id}>{s.name} ({s.class})</option>)}</select></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Centre *</label><select value={form.centerId} onChange={e => setForm({...form,centerId:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{centers.map(c => <option key={c.id} value={c.id}>{c.name} ({c.service})</option>)}</select></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Service</label><input value={form.service} onChange={e => setForm({...form,service:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Service" /></div><div><label className="block text-sm text-slate-400 mb-1">Date début</label><input type="date" value={form.startDate} onChange={e => setForm({...form,startDate:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" /></div><div><label className="block text-sm text-slate-400 mb-1">Date fin</label><input type="date" value={form.endDate} onChange={e => setForm({...form,endDate:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" /></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Statut</label><select value={form.status} onChange={e => setForm({...form,status:e.target.value as any})} className="w-full input-glass rounded-xl px-4 py-3">{statusOptions.map(s => <option key={s} value={s}>{s}</option>)}</select></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsModal(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleSubmit} className="btn-gold rounded-xl px-6 py-2.5">Affecter</button></div></Modal>
      <Modal isOpen={isCenter} onClose={() => setIsCenter(false)} title="Ajouter un centre"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Nom *</label><input value={cForm.name} onChange={e => setCForm({...cForm,name:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Nom du centre" /></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Service</label><input value={cForm.service} onChange={e => setCForm({...cForm,service:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Service" /></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Capacité</label><input type="number" value={cForm.capacity} onChange={e => setCForm({...cForm,capacity:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="0" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsCenter(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleCenter} className="btn-gold rounded-xl px-6 py-2.5">Ajouter</button></div></Modal>
    </div>
  );
}
