import { useState, useMemo } from 'react'; import { motion } from 'framer-motion'; import { BookOpen, Plus, Trash2 } from 'lucide-react'; import { useApp, CLASSES, generateId } from '../context/AppContext'; import Modal from '../components/Modal';
const terms = ['Année','Semestre 1','Semestre 2','Semestre 3','Semestre 4','Semestre 5','Semestre 6'];
export default function Subjects() {
  const { subjects, addSubject } = useApp(); const [cf, setCf] = useState(''); const [tf, setTf] = useState(''); const [isModal, setIsModal] = useState(false);
  const [form, setForm] = useState({ className:'', unit:'', name:'', credits:'', term:'Année' });
  const filtered = useMemo(() => { let r = subjects; if (cf) r = r.filter(s => s.className === cf); if (tf) r = r.filter(s => s.term === tf); return r; }, [subjects, cf, tf]);
  const handleSubmit = () => { if (!form.name || !form.className) return; addSubject({ id: generateId(), className: form.className, unit: form.unit, name: form.name, credits: Number(form.credits) || 0, term: form.term }); setIsModal(false); setForm({ className:'', unit:'', name:'', credits:'', term:'Année' }); };
  return (
    <div>
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-white mb-1">Matières et crédits</h2><p className="text-slate-400 text-sm">{filtered.length} matières enregistrées</p></div><button onClick={() => setIsModal(true)} className="btn-gold rounded-xl px-5 py-2.5 flex items-center gap-2 text-sm"><Plus size={18} /> Ajouter</button></div>
      <div className="glass-panel rounded-xl p-4 mb-6 flex flex-col md:flex-row gap-4"><select value={cf} onChange={e => setCf(e.target.value)} className="input-glass rounded-xl px-4 py-2.5"><option value="">Toutes les classes</option>{CLASSES.map(c => <option key={c} value={c}>{c}</option>)}</select><select value={tf} onChange={e => setTf(e.target.value)} className="input-glass rounded-xl px-4 py-2.5"><option value="">Tous les semestres</option>{terms.map(t => <option key={t} value={t}>{t}</option>)}</select></div>
      <div className="glass-panel rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Classe</th><th>Semestre</th><th>Unité</th><th>Matière</th><th>Crédits</th></tr></thead><tbody>
        {filtered.map((s, i) => (<motion.tr key={s.id} initial={{ opacity:0, x:-20 }} animate={{ opacity:1, x:0 }} transition={{ delay:i*0.01 }}><td><span className="badge-blue">{s.className}</span></td><td>{s.term}</td><td className="font-mono text-amber-400/80">{s.unit}</td><td className="font-medium text-white">{s.name}</td><td className="font-semibold">{s.credits}</td></motion.tr>))}
      </tbody></table></div>{filtered.length===0 && <div className="p-12 text-center"><BookOpen className="mx-auto mb-4 text-slate-600" size={48} /><p className="text-slate-500">Aucune matière trouvée</p></div>}</div>
      <Modal isOpen={isModal} onClose={() => setIsModal(false)} title="Ajouter une matière"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className="block text-sm text-slate-400 mb-1">Classe *</label><select value={form.className} onChange={e => setForm({...form,className:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{CLASSES.map(c => <option key={c} value={c}>{c}</option>)}</select></div><div><label className="block text-sm text-slate-400 mb-1">Semestre</label><select value={form.term} onChange={e => setForm({...form,term:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3">{terms.map(t => <option key={t} value={t}>{t}</option>)}</select></div><div><label className="block text-sm text-slate-400 mb-1">Unité</label><input value={form.unit} onChange={e => setForm({...form,unit:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Ex: SIO 111" /></div><div><label className="block text-sm text-slate-400 mb-1">Crédits</label><input type="number" value={form.credits} onChange={e => setForm({...form,credits:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="0" /></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Nom de la matière *</label><input value={form.name} onChange={e => setForm({...form,name:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Nom complet" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsModal(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleSubmit} className="btn-gold rounded-xl px-6 py-2.5">Ajouter</button></div></Modal>
    </div>
  );
}
