import { useState, useMemo } from 'react'; import { motion } from 'framer-motion'; import { Eye, Plus, Trash2 } from 'lucide-react'; import { useApp, CLASSES, generateId } from '../context/AppContext'; import Modal from '../components/Modal';
export default function Supervision() {
  const { supervisions, addSupervision, deleteSupervision } = useApp(); const [isModal, setIsModal] = useState(false);
  const [form, setForm] = useState({ date:'', supervisor:'', terrain:'', service:'', className:'', absents:'', observation:'' });
  const handleSubmit = () => { if (!form.supervisor || !form.terrain) return; addSupervision({ id: generateId(), date: form.date || new Date().toISOString().split('T')[0], supervisor: form.supervisor, terrain: form.terrain, service: form.service, className: form.className, absents: form.absents, observation: form.observation }); setIsModal(false); setForm({ date:'', supervisor:'', terrain:'', service:'', className:'', absents:'', observation:'' }); };
  return (
    <div>
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-white mb-1">Supervision des stages</h2><p className="text-slate-400 text-sm">{supervisions.length} supervisions enregistrées</p></div><button onClick={() => setIsModal(true)} className="btn-gold rounded-xl px-5 py-2.5 flex items-center gap-2 text-sm"><Plus size={18} /> Planifier</button></div>
      <div className="glass-panel rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="table-glass"><thead><tr><th>Date</th><th>Superviseur</th><th>Terrain</th><th>Service</th><th>Classe</th><th>Absents</th><th>Observation</th><th></th></tr></thead><tbody>
        {supervisions.map((s, i) => (<motion.tr key={s.id} initial={{ opacity:0, x:-20 }} animate={{ opacity:1, x:0 }} transition={{ delay:i*0.03 }}><td>{s.date}</td><td className="font-medium text-white">{s.supervisor}</td><td>{s.terrain}</td><td>{s.service}</td><td><span className="badge-blue">{s.className}</span></td><td className="text-red-400">{s.absents}</td><td>{s.observation}</td><td><button onClick={() => deleteSupervision(s.id)} className="p-2 rounded-lg hover:bg-red-500/10 text-red-400"><Trash2 size={16} /></button></td></motion.tr>))}
      </tbody></table></div>{supervisions.length===0 && <div className="p-12 text-center"><Eye className="mx-auto mb-4 text-slate-600" size={48} /><p className="text-slate-500">Aucune supervision enregistrée</p></div>}</div>
      <Modal isOpen={isModal} onClose={() => setIsModal(false)} title="Planifier une supervision"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className="block text-sm text-slate-400 mb-1">Date</label><input type="date" value={form.date} onChange={e => setForm({...form,date:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" /></div><div><label className="block text-sm text-slate-400 mb-1">Superviseur *</label><input value={form.supervisor} onChange={e => setForm({...form,supervisor:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Nom du superviseur" /></div><div><label className="block text-sm text-slate-400 mb-1">Terrain</label><input value={form.terrain} onChange={e => setForm({...form,terrain:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Structure de santé" /></div><div><label className="block text-sm text-slate-400 mb-1">Service</label><input value={form.service} onChange={e => setForm({...form,service:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Service" /></div><div><label className="block text-sm text-slate-400 mb-1">Classe</label><select value={form.className} onChange={e => setForm({...form,className:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3"><option value="">Choisir...</option>{CLASSES.map(c => <option key={c} value={c}>{c}</option>)}</select></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Absents</label><input value={form.absents} onChange={e => setForm({...form,absents:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Noms des absents" /></div><div className="md:col-span-2"><label className="block text-sm text-slate-400 mb-1">Observation</label><input value={form.observation} onChange={e => setForm({...form,observation:e.target.value})} className="w-full input-glass rounded-xl px-4 py-3" placeholder="Observation" /></div></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setIsModal(false)} className="px-6 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-colors">Annuler</button><button onClick={handleSubmit} className="btn-gold rounded-xl px-6 py-2.5">Planifier</button></div></Modal>
    </div>
  );
}
